tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:Pl1u04UFhyhOGFkyGfqv0aBHeQu2w0SGeg==,iv:x6Lop229q51i4YbI7dSVgCPhVbRV9QglJU0lCLYLvX0=,tag:dJhb2d5wsmPVaf2i/6omOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c4xv3zq2jle4eyczvju97skzhnrxxy889xtektnmpr5amps0s4hsnf4vhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd0pBcFFhNmc3dTNqR3Rj
            WHE5Sk04L0x6ZlZScGhUcTByYjRYNWxoZTFjCkxKdDNaQVV6NVgrLzNVWGp5bTUv
            Snh5QjlNUzRwVjhFdDdjZjc0NVpOOEkKLS0tIDkzL3ZEVGllaUpNUVU1U05iWjVm
            QU1kaENGeXh6S1oxQUo5Q2s3UHBCTkkKOHyF0CPhd4bWpcoRJ+CoCkpeFQB0xyoH
            WqmvkebxIpPBnVCR3Iw21x89PlPHBLgokrGjMoZqiFaYFMQS2fizfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-24T15:28:08Z"
    mac: ENC[AES256_GCM,data:0oJCOc2WWQLimR73kiq63yC5PLsBh0FaDziVa/32LZbogfVfSX/fdtsg4AYAZFGBIrW0jvnKcDgbGzDWfs3lI5AnIJHnSlWCmb9Fe4b6cwShDjBnwtUfZtESzUvUo1Np4OgvmBHfc/gHrZ4ThHQeH6rpGDc/H3HuvbZ4uB1rVho=,iv:DjZ12+/WJX5hNfJhGA9zQLj92SdPTvW5Qdm74LR6DxI=,tag:alE+G+QVhRime1xxq8m0lg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
